# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0002_auto_20160125_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('fromstamp', models.DateField(blank=True, null=True)),
                ('tostamp', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='carshare.Agency')),
            ],
            options={
                'ordering': ['plate'],
                'verbose_name': 'Autorizzazione',
                'verbose_name_plural': 'Autorizzazioni',
            },
        ),
    ]
